name: Import standard labels

on:
  push:
    branches: [main]

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Delete existing labels
        run: |
          echo "GitHub Token: ${{ secrets.github-token }}"
          if [ "${{ inputs.force }}" = true ]; then
            npx ghlbl -o ${{ inputs.owner-name }} -r ${{ inputs.repository-name }} -t ${{ secrets.github-token }} -d
          else
            echo -e "Existing labels not removed"
          fi
        shell: bash

      - name: Import labels from json file
        run: npx ghlbl -o ${{ inputs.owner-name }} -r ${{ inputs.repository-name }} -t ${{ secrets.github-token }} -i ${{ github.action_path }}/labels.json
        shell: bash
